apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: $CIRCLE_PROJECT_REPONAME-ingress
spec:
  tls:
    - hosts:
        - $CIRCLE_PROJECT_REPONAME.makewebtech.org
      secretName: $CIRCLE_PROJECT_REPONAME-ingress-tls
  rules:
    - host: $CIRCLE_PROJECT_REPONAME.makewebtech.org
      http:
        paths:
          - backend:
              serviceName: $CIRCLE_PROJECT_REPONAME
              servicePort: 80
---
apiVersion: cert-manager.io/v1alpha2 # kubectl describe certificate echo1-certificate
kind: Certificate
metadata:
  name: $CIRCLE_PROJECT_REPONAME-certificate
  namespace: $CIRCLE_PROJECT_REPONAME
spec:
  secretName: $CIRCLE_PROJECT_REPONAME-ingress-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: $CIRCLE_PROJECT_REPONAME.makewebtech.org
  dnsNames:
    - $CIRCLE_PROJECT_REPONAME.makewebtech.org
---
apiVersion: v1
kind: Service
metadata:
  name: $CIRCLE_PROJECT_REPONAME
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: $CIRCLE_PROJECT_REPONAME
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $CIRCLE_PROJECT_REPONAME
spec:
  selector:
    matchLabels:
      app: $CIRCLE_PROJECT_REPONAME
  replicas: 2
  template:
    metadata:
      labels:
        app: $CIRCLE_PROJECT_REPONAME
    spec:
      containers:
        - name: $CIRCLE_PROJECT_REPONAME
          image: $DOCKERHUB_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
          ports:
            - containerPort: 3000
