version: 2.1

refs:
  - &only_master
    filters:
      branches:
        only: master

  - &not_master
    filters:
      branches:
        ignore: master

workflows:
  test:
    jobs:
      - unit-tests:
          <<: *not_master
          name: node-8
          version: '8'
      - unit-tests:
          <<: *not_master
          name: node-10
          version: '10'
      - unit-tests:
          <<: *not_master
          name: node-12
          version: '12'

  release:
    jobs:
      - unit-tests:
          <<: *only_master
          name: node-8
          version: '8'
      - unit-tests:
          <<: *only_master
          name: node-10
          version: '10'
      - unit-tests:
          <<: *only_master
          name: node-12
          version: '12'

      - publish-dry-run:
          <<: *only_master
          context: common-env

      - publish-approval:
          type: approval
          context: common-env
          requires:
            - publish-dry-run

      - publish:
          <<: *only_master
          context: common-env
          requires:
            - node-8
            - node-10
            - node-12
            - publish-approval

jobs:
  unit-tests:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/node:<< parameters.version >>
    steps:
      - setup
      - build
      - test

  deploy-staging:
    docker:
      - image: circleci/node:12
    steps:
      - setup
      - build
      - authenticate
      - push
      - deploy-staging

  deploy-production:
    docker:
      - image: circleci/node:12
    steps:
      - authenticate
      - deploy-production

commands:
  setup:
    description: 'Checkout and install dependencies'
    steps:
      - checkout
      - run:
          name: Versions
          command: node -v && npm -v && yarn -v
      - run:
          name: Install Dependencies
          command: yarn install --pure-lockfile

  build:
    steps:
      - run:
          name: Build
          command: yarn build

  test:
    steps:
      - run:
          name: Test
          command: yarn test

  authenticate:
    steps:
      - add_ssh_keys:
          fingerprints:
            - '2f:e6:90:bb:61:85:fe:d5:9a:1a:27:77:9e:09:8d:fd'

  push:
    steps:
      - run:
          name: Build Docker
          command: docker build -t dokku/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 .
      - run:
          name: Push Docker
          command: docker save dokku/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 | bzip2 | pv | ssh root@$DOKKU_SERVER "bunzip2 | docker load"

  deploy-staging:
    steps:
      - run:
          name: Tag Docker (Staging)
          command: ssh root@$DOKKU_SERVER "docker tag dokku/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1 dokku/$CIRCLE_PROJECT_REPONAME-staging:$CIRCLE_SHA1"
      - run:
          name: Push Docker (Staging)
          command: ssh root@$DOKKU_SERVER "dokku tags:deploy $CIRCLE_PROJECT_REPONAME-staging $CIRCLE_SHA1"

  deploy-production:
    steps:
      - run:
          name: Push Docker (Production)
          command: ssh root@$DOKKU_SERVER "dokku tags:deploy $CIRCLE_PROJECT_REPONAME $CIRCLE_SHA1"
